### ISSUE TITLE
Wiki tips

### ISSUE THREAD

**Issue by CountNick** [WesselSmit/frontend-data#9]
It seems like all information regarding your concept is in the weekly diary:clown_face: It might be a good idea to split all main documentation things into pages of it's own for instance: 

Table of contents 

1 - Debriefing
2 - Ideation
3 - Concept

etc. 

You can use you're homepage as a table of contents which links to these pages. This makes it easier to jump to specific segments of your wiki:tada:

**Comment by WesselSmit** [comment]
added table of contents

all main documentation topics will have their own 'chapter'/page
